class DBQuery:
    GET_USER_DETAILS = "SELECT ID, UserMail, Password, FirstName, LastName, UserType  FROM UsersMaster WHERE UserMail = ?"


class DBQueryForDashboardAttorney:
    # Projects
    MY_OPEN_PROJECTS = "Select Count(*) AS 'TotalProjectCount' From [Project] Where LegalResourceAttorneyID1 = ? AND ProjectPrimaryStatus IN ('Open')"
    FIRM_OPEN_PROJECTS = "Select Count(*) AS 'TotalProjectCount' From [Project] Where ProjectPrimaryStatus IN ('Open')"
    # Total  Petitioners
    FIRM_PETITIONER = "Select Count(*) AS 'TotalPetitionerCount' From Petitioner Where [Status] = 'Active'"
    MY_PETITIONER = "Select Count(*) AS 'TotalPetitionerCount' From Petitioner Where [Status] = 'Active' AND WorkingAttorney = ?"
    # Total New Petitioners
    NEW_FIRM_PETITIONER = "Select Count(*) AS 'TotalPetitionerCount' From Petitioner Where [Status] = 'active' AND IIF(OpenDate = NULL, CreatedDate, OpenDate) Between '2023-01-01' AND '2023-12-01'"
    NEW_MY_PETITIONER = "Select Count(*) AS 'TotalPetitionerCount' From Petitioner Where [Status] = 'active' AND WorkingAttorney = ? AND IIF(OpenDate = NULL, CreatedDate, OpenDate)  Between '2023-01-01' AND '2023-12-01'"
    # Total Beneficiary
    FIRM_BENEFICIARY = "Select Count(*) AS 'TotalBeneficiaryCount' From Beneficiary Where [Status] = 'Active'"
    MY_BENEFICIARY = "Select Count(*) AS 'TotalBeneficiaryCount' From Beneficiary Where [Status] = 'active' AND WorkingAttorneyID = ?"
    # Total New Beneficiary
    NEW_FIRM_BENEFICIARY = "Select Count(*) AS 'TotalBeneficiaryCount' From Beneficiary Where [Status] = 'Active' AND CreatedDate Between '2023-01-01' AND '2023-12-01'"
    NEW_MY_BENEFICIARY = "Select Count(*) AS 'TotalBeneficiaryCount' From Beneficiary Where [Status] = 'Active' AND WorkingAttorneyID = ? AND CreatedDate Between '2023-01-01' AND '2023-12-01'"
    # Project Filed
    PROJECT_FILED_THIS = "Select FORMAT(x.ProjectFiledDate, 'MMM') as 'MonthName', x.TotalCount from (Select ProjectFiledDate = DATEADD(MONTH, DATEDIFF(MONTH, 0, ProjectFiledDate), 0), COUNT(*) As 'TotalCount' FROM [Project] WHERE ProjectFiledDate Between '2023-01-01' AND '2023-12-01' GROUP BY DATEADD(MONTH, DATEDIFF(MONTH, 0, ProjectFiledDate), 0)) x ORDER BY ProjectFiledDate ASC"
    PROJECT_FILED_PREV = "Select FORMAT(x.ProjectFiledDate, 'MMM') as 'MonthName', x.TotalCount from (Select ProjectFiledDate = DATEADD(MONTH, DATEDIFF(MONTH, 0, ProjectFiledDate), 0), COUNT(*) As 'TotalCount' FROM [Project] WHERE ProjectFiledDate Between '2022-01-01' AND '2022-12-01' GROUP BY DATEADD(MONTH, DATEDIFF(MONTH, 0, ProjectFiledDate), 0)) x ORDER BY ProjectFiledDate ASC"
    # Project Initiated
    PROJECT_INITIATED_THIS = "Select FORMAT(x.CreatedDate, 'MMM') as 'MonthName', x.TotalCount from (Select CreatedDate = DATEADD(MONTH, DATEDIFF(MONTH, 0, CreatedDate), 0), COUNT(*) As 'TotalCount' FROM [Project] WHERE CreatedDate Between '2023-01-01' AND '2023-12-01' GROUP BY DATEADD(MONTH, DATEDIFF(MONTH, 0, CreatedDate), 0)) x ORDER BY CreatedDate ASC"
    PROJECT_INITIATED_PREV = "Select FORMAT(x.CreatedDate, 'MMM') as 'MonthName', x.TotalCount from (Select CreatedDate = DATEADD(MONTH, DATEDIFF(MONTH, 0, CreatedDate), 0), COUNT(*) As 'TotalCount' FROM [Project] WHERE CreatedDate Between '2022-01-01' AND '2022-12-01' GROUP BY DATEADD(MONTH, DATEDIFF(MONTH, 0, CreatedDate), 0)) x ORDER BY CreatedDate ASC"
    # Open Projects By Para
    OPEN_PROJECTS_PARA = """Select LegalResourceAttorneyID1, Count(ProjectID) AS 'CountOFProject', LegalResourceStaffID1, LegalResource.FirstName, LegalResource.LastName From [Project], LegalResource Where LegalResourceStaffID1 IN (Select LegalResourceStaffID1 From [Project] Where LegalResourceAttorneyID1  = ? 
        AND ProjectPrimaryStatus IN ('Open')) AND [Project].LegalResourceStaffID1 = LegalResource.LegalResourceEmployeeId AND LegalResourceAttorneyID1  = ? AND ProjectPrimaryStatus IN ('Open') Group BY LegalResourceStaffID1, LegalResource.FirstName, LegalResource.LastName, LegalResourceAttorneyID1"""


class DBQueryForDashboardHR:
    # Projects
    MY_OPEN_PROJECTS = "Select Count(*) AS 'TotalProjectCount' From [Project] Where [Project].HRContactID = ? AND ProjectPrimaryStatus IN ('Open')"
    FIRM_OPEN_PROJECTS = "Select Count(*) AS 'TotalProjectCount' From [Project] Where ProjectPrimaryStatus IN ('Open')"
    # Total Petitioners
    FIRM_PETITIONER = "Select Count(*) AS 'TotalPetitionerCount' From Petitioner Where [Status] = 'Active'"
    MY_PETITIONER = "Select Count(*) AS 'TotalPetitionerCount' From Petitioner Where Petitioner.[Status] = 'Active' AND HRContactID = ?"
    # Total New Petitioners
    NEW_FIRM_PETITIONER = "Select Count(*) AS 'TotalPetitionerCount' From Petitioner Where [Status] = 'Active' AND CreatedDate Between '2023-01-01' AND '2023-12-01'"
    NEW_MY_PETITIONER = "Select Count(*) AS 'TotalPetitionerCount' From Petitioner Where Petitioner.[Status] = 'Active' AND HRContactID = ? AND IIF(OpenDate = NULL, CreatedDate, OpenDate) Between '2023-01-01' AND '2023-12-01'"
    # Total Beneficiary
    FIRM_BENEFICIARY = "Select Count(*) AS 'TotalBeneficiaryCount' From Beneficiary Where [Status] = 'Active'"
    MY_BENEFICIARY = "Select Count(*) AS 'TotalBeneficiaryCount' From Beneficiary, [Project] Where Beneficiary.[Status] = 'Active' AND Beneficiary.BeneficiaryID = [Project].BeneficiaryID AND [Project].HRContactID = ?"
    # Total New Petitioners
    NEW_FIRM_BENEFICIARY = "Select Count(*) AS 'TotalBeneficiaryCount' From Beneficiary Where [Status] = 'Active' AND CreatedDate Between '2023-01-01' AND '2023-12-01'"
    NEW_MY_BENEFICIARY = "Select Count(*) AS 'TotalBeneficiaryCount' From Beneficiary, [Project] Where Beneficiary.[Status] = 'Active' AND Beneficiary.BeneficiaryID = [Project].BeneficiaryID AND HRContactID = ? AND Beneficiary.CreatedDate Between '2023-01-01' AND '2023-12-01'"
    # Project Filed
    PROJECT_FILED_THIS = "Select FORMAT(x.ProjectFiledDate, 'MMM') as 'MonthName', x.TotalCount from (SELECT  ProjectFiledDate = DATEADD(MONTH, DATEDIFF(MONTH, 0, ProjectFiledDate), 0),COUNT(*) As 'TotalCount' FROM [Project], Beneficiary Where [Project].BeneficiaryID = Beneficiary.BeneficiaryID AND [Project].HRContactID = ? AND [Project].ProjectFiledDate Between '2023-01-01' AND '2023-12-01' GROUP BY DATEADD(MONTH, DATEDIFF(MONTH, 0, ProjectFiledDate), 0)) x ORDER BY ProjectFiledDate ASC"
    PROJECT_FILED_PREV = "Select FORMAT(x.ProjectFiledDate, 'MMM') as 'MonthName', x.TotalCount from (SELECT  ProjectFiledDate = DATEADD(MONTH, DATEDIFF(MONTH, 0, ProjectFiledDate), 0),COUNT(*) As 'TotalCount' FROM [Project], Beneficiary Where [Project].BeneficiaryID = Beneficiary.BeneficiaryID AND [Project].HRContactID = ? AND [Project].ProjectFiledDate Between '2022-01-01' AND '2022-12-01' GROUP BY DATEADD(MONTH, DATEDIFF(MONTH, 0, ProjectFiledDate), 0)) x ORDER BY ProjectFiledDate ASC"
    # Project Initiated
    PROJECT_INITIATED_THIS = "Select FORMAT(x.CreatedDate, 'MMM') as 'MonthName', x.TotalCount from (SELECT CreatedDate = DATEADD(MONTH, DATEDIFF(MONTH, 0, [Project].CreatedDate), 0),COUNT(*) As 'TotalCount' FROM    [Project], Beneficiary Where [Project].BeneficiaryID = Beneficiary.BeneficiaryID AND [Project].HRContactID = ? AND [Project].CreatedDate Between '2023-01-01' AND '2023-12-01' GROUP BY DATEADD(MONTH, DATEDIFF(MONTH, 0, [Project].CreatedDate), 0)) x ORDER BY CreatedDate ASC"
    PROJECT_INITIATED_PREV = "Select FORMAT(x.CreatedDate, 'MMM') as 'MonthName', x.TotalCount from (SELECT CreatedDate = DATEADD(MONTH, DATEDIFF(MONTH, 0, [Project].CreatedDate), 0),COUNT(*) As 'TotalCount' FROM    [Project], Beneficiary Where [Project].BeneficiaryID = Beneficiary.BeneficiaryID AND [Project].HRContactID = ? AND [Project].CreatedDate Between '2022-01-01' AND '2022-12-01' GROUP BY DATEADD(MONTH, DATEDIFF(MONTH, 0, [Project].CreatedDate), 0)) x ORDER BY CreatedDate ASC"
    # Open Projects By Para
    OPEN_PROJECTS_PARA = """Select Count(ProjectID) AS 'CountOFProject', LegalResourceStaffID1, LegalResource.FirstName, LegalResource.LastName From [Project], LegalResource Where LegalResourceStaffID1 IN (Select LegalResourceStaffID1 From [Project] Where [Project].HRContactID = ? 
        AND ProjectPrimaryStatus IN ('Open')) AND [Project].LegalResourceStaffID1 = LegalResource.LegalResourceEmployeeId AND [Project].HRContactID  = ? AND ProjectPrimaryStatus IN ('Open') Group BY LegalResourceStaffID1, LegalResource.FirstName, LegalResource.LastName"""


class DBQueryForDashboardParalegal:
    # Projects
    MY_OPEN_PROJECTS = "Select Count(*) AS 'TotalProjectCount' From [Project] Where LegalResourceStaffID1 = ? AND ProjectPrimaryStatus IN ('Open')"
    FIRM_OPEN_PROJECTS = "Select Count(*) AS 'TotalProjectCount' From [Project] Where ProjectPrimaryStatus IN ('Open')"
    # Total Petitioners
    FIRM_PETITIONER = "Select Count(*) AS 'TotalPetitionerCount' From Petitioner Where [Status] = 'active'"
    MY_PETITIONER = "Select Count(*) AS 'TotalPetitionerCount' From Petitioner Where Petitioner.[Status] = 'active' AND PetitionerID IN (Select Beneficiary.PetitionerID From Beneficiary Where BeneficiaryID IN (Select Project.BeneficiaryID From Project Where LegalResourceStaffID1 = ?))"
    # Total New Petitioners
    NEW_FIRM_PETITIONER = "Select Count(*) AS 'TotalPetitionerCount' From Petitioner Where [Status] = 'active' AND CreatedDate Between '2023-01-01' AND '2023-12-01'"
    NEW_MY_PETITIONER = "Select Count(*) AS 'TotalPetitionerCount' From Petitioner Where Petitioner.[Status] = 'active' AND PetitionerID IN (Select Beneficiary.PetitionerID From Beneficiary Where BeneficiaryID IN (Select Project.BeneficiaryID From Project Where LegalResourceStaffID1 = ?)) AND Petitioner.CreatedDate Between '2023-01-01' AND '2023-12-01'"
    # Total Beneficiary
    FIRM_BENEFICIARY = "Select Count(*) AS 'TotalBeneficiaryCount' From Beneficiary Where [Status] = 'active'"
    MY_BENEFICIARY = "Select Count(*) AS 'TotalBeneficiaryCount' From Beneficiary, [Project] Where Beneficiary.[Status] = 'active' AND Beneficiary.BeneficiaryID = [Project].BeneficiaryID AND LegalResourceStaffID1 = ?"
    # Total New Beneficiary
    NEW_FIRM_BENEFICIARY = "Select Count(*) AS 'TotalBeneficiaryCount' From Beneficiary, [Project] Where Beneficiary.[Status] = 'active' AND Beneficiary.BeneficiaryID = [Project].BeneficiaryID AND Beneficiary.CreatedDate Between '2023-01-01' AND '2023-12-01'"
    NEW_MY_BENEFICIARY = "Select Count(*) AS 'TotalBeneficiaryCount' From Beneficiary, [Project] Where Beneficiary.[Status] = 'active' AND Beneficiary.CreatedDate Between '2023-01-01' AND '2023-12-01' AND Beneficiary.BeneficiaryID = [Project].BeneficiaryID AND LegalResourceStaffID1 = ?"
    # Project Filed
    PROJECT_FILED_THIS = "Select FORMAT(x.ProjectFiledDate, 'MMM') as 'MonthName', x.TotalCount from (SELECT  ProjectFiledDate = DATEADD(MONTH, DATEDIFF(MONTH, 0, ProjectFiledDate), 0),COUNT(*) As 'TotalCount' FROM    [Project], Beneficiary Where [Project].BeneficiaryID = Beneficiary.BeneficiaryID AND LegalResourceStaffID1 = ?  AND [Project].ProjectFiledDate Between '2023-01-01' AND '2023-12-01' GROUP BY DATEADD(MONTH, DATEDIFF(MONTH, 0, ProjectFiledDate), 0)) x ORDER BY ProjectFiledDate ASC"
    PROJECT_FILED_PREV = "Select FORMAT(x.ProjectFiledDate, 'MMM') as 'MonthName', x.TotalCount from (SELECT  ProjectFiledDate = DATEADD(MONTH, DATEDIFF(MONTH, 0, ProjectFiledDate), 0),COUNT(*) As 'TotalCount' FROM    [Project], Beneficiary Where [Project].BeneficiaryID = Beneficiary.BeneficiaryID AND LegalResourceStaffID1 = ?  AND [Project].ProjectFiledDate Between '2022-01-01' AND '2022-12-01' GROUP BY DATEADD(MONTH, DATEDIFF(MONTH, 0, ProjectFiledDate), 0)) x ORDER BY ProjectFiledDate ASC"
    # Project Initiated
    PROJECT_INITIATED_THIS = "Select FORMAT(x.CreatedDate, 'MMM') as 'MonthName', x.TotalCount from (SELECT CreatedDate = DATEADD(MONTH, DATEDIFF(MONTH, 0, [Project].CreatedDate), 0),COUNT(*) As 'TotalCount' FROM    [Project], Beneficiary Where [Project].BeneficiaryID = Beneficiary.BeneficiaryID AND LegalResourceStaffID1 = ?  AND [Project].CreatedDate Between '2023-01-01' AND '2023-12-01' GROUP BY DATEADD(MONTH, DATEDIFF(MONTH, 0, [Project].CreatedDate), 0)) x ORDER BY CreatedDate ASC"
    PROJECT_INITIATED_PREV = "Select FORMAT(x.CreatedDate, 'MMM') as 'MonthName', x.TotalCount from (SELECT CreatedDate = DATEADD(MONTH, DATEDIFF(MONTH, 0, [Project].CreatedDate), 0),COUNT(*) As 'TotalCount' FROM    [Project], Beneficiary Where [Project].BeneficiaryID = Beneficiary.BeneficiaryID AND LegalResourceStaffID1 = ?  AND [Project].CreatedDate Between '2022-01-01' AND '2022-12-01' GROUP BY DATEADD(MONTH, DATEDIFF(MONTH, 0, [Project].CreatedDate), 0)) x ORDER BY CreatedDate ASC"
    # Open Projects By Para
    OPEN_PROJECTS_PARA = """Select LegalResourceAttorneyID1, Count(ProjectID) AS 'CountOFProject', LegalResourceStaffID1, LegalResource.FirstName, LegalResource.LastName From [Project], LegalResource Where LegalResourceStaffID1 IN (Select LegalResourceStaffID1 From [Project] Where [Project].LegalResourceStaffID1  = ?
        AND ProjectPrimaryStatus IN ('Open')) AND [Project].LegalResourceStaffID1 = LegalResource.LegalResourceEmployeeId AND [Project].LegalResourceStaffID1  = ? AND ProjectPrimaryStatus IN ('Open') Group BY LegalResourceStaffID1, LegalResource.FirstName, LegalResource.LastName, LegalResourceAttorneyID1"""


class DBQueryForDashboardBeneficiary:
    # Projects
    MY_OPEN_PROJECTS = "Select Count(*) AS 'TotalProjectCount' From [Project] Where [Project].BeneficiaryID = ? AND ProjectPrimaryStatus IN ('Open')"
    FIRM_OPEN_PROJECTS = "Select Count(*) AS 'TotalProjectCount' From [Project] Where ProjectPrimaryStatus IN ('Open')"
    # Total Petitioners
    FIRM_PETITIONER = "Select Count(*) AS 'TotalPetitionerCount' From Petitioner Where [Status] = 'Active'"
    MY_PETITIONER = "Select Count(*) AS 'TotalPetitionerCount' From Petitioner Where Petitioner.[Status] = 'Active' AND PetitionerID IN (Select Beneficiary.PetitionerID From Beneficiary Where BeneficiaryID = ? Group BY Beneficiary.PetitionerID)"
    # Total New Petitioners
    NEW_FIRM_PETITIONER = "Select Count(*) AS 'TotalPetitionerCount' From Petitioner Where [Status] = 'Active' AND CreatedDate Between '2023-01-01' AND '2023-12-01'"
    NEW_MY_PETITIONER = "Select Count(*) AS 'TotalPetitionerCount' From Petitioner Where Petitioner.[Status] = 'Active' AND PetitionerID IN (Select Beneficiary.PetitionerID From Beneficiary Where BeneficiaryID = ? Group BY Beneficiary.PetitionerID) AND CreatedDate Between '2023-01-01' AND '2023-12-01'"
    # Total Beneficiary
    FIRM_BENEFICIARY = "Select Count(*) AS 'TotalBeneficiaryCount' From Beneficiary Where [Status] = 'Active'"
    MY_BENEFICIARY = "Select Count(*) AS 'TotalBeneficiaryCount' From Beneficiary, [Project] Where Beneficiary.[Status] = 'Active' AND Beneficiary.BeneficiaryID = [Project].BeneficiaryID AND Beneficiary.BeneficiaryID = ?"
    # Total New Beneficiary
    NEW_FIRM_BENEFICIARY = "Select Count(*) AS 'TotalBeneficiaryCount' From Beneficiary, [Project] Where Beneficiary.[Status] = 'Active' AND Beneficiary.BeneficiaryID = [Project].BeneficiaryID AND [Project].BeneficiaryID = ? AND Beneficiary.CreatedDate Between '2023-01-01' AND '2023-12-01'"
    NEW_MY_BENEFICIARY = "Select Count(*) AS 'TotalBeneficiaryCount' From Beneficiary, [Project] Where Beneficiary.[Status] = 'Active' AND Beneficiary.CreatedDate Between '2023-01-01' AND '2023-12-01' AND [Project].BeneficiaryID = ?"
    # Project Filed
    PROJECT_FILED_THIS = "SELECT  ProjectFiledDate = DATEADD(MONTH, DATEDIFF(MONTH, 0, ProjectFiledDate), 0),COUNT(*) As 'TotalCount' FROM    [Project], Beneficiary Where ProjectFiledDate Between '2023-01-01' AND '2023-12-01' AND Beneficiary.BeneficiaryID = [Project].BeneficiaryID AND [Project].BeneficiaryID = ? GROUP BY DATEADD(MONTH, DATEDIFF(MONTH, 0, ProjectFiledDate), 0)"
    PROJECT_FILED_PREV = "SELECT  ProjectFiledDate = DATEADD(MONTH, DATEDIFF(MONTH, 0, ProjectFiledDate), 0),COUNT(*) As 'TotalCount' FROM    [Project], Beneficiary Where ProjectFiledDate Between '2022-01-01' AND '2022-12-01' AND Beneficiary.BeneficiaryID = [Project].BeneficiaryID AND [Project].BeneficiaryID = ? GROUP BY DATEADD(MONTH, DATEDIFF(MONTH, 0, ProjectFiledDate), 0)"
    # Project Initiated
    PROJECT_INITIATED_THIS = "SELECT CreatedDate = DATEADD(MONTH, DATEDIFF(MONTH, 0, [Project].CreatedDate), 0),COUNT(*) As 'TotalCount' FROM    [Project], Beneficiary Where [Project].CreatedDate Between '2023-01-01' AND '2023-12-01' AND Beneficiary.BeneficiaryID = [Project].BeneficiaryID AND [Project].BeneficiaryID = ? GROUP BY DATEADD(MONTH, DATEDIFF(MONTH, 0, [Project].CreatedDate), 0)"
    PROJECT_INITIATED_PREV = "SELECT CreatedDate = DATEADD(MONTH, DATEDIFF(MONTH, 0, [Project].CreatedDate), 0),COUNT(*) As 'TotalCount' FROM    [Project], Beneficiary Where [Project].CreatedDate Between '2022-01-01' AND '2022-12-01' AND Beneficiary.BeneficiaryID = [Project].BeneficiaryID AND [Project].BeneficiaryID = ? GROUP BY DATEADD(MONTH, DATEDIFF(MONTH, 0, [Project].CreatedDate), 0)"


class DBQueryForPetitioner:
    # Get Petitioner By ID
    PET_BY_ID = "Select * From Petitioner Where PetitionerID = ?"
    # Get Petitioner List By User
    PET_BY_ATTORNEY = "Select PetitionerID, PetitionerName From Petitioner Where WorkingAttorney = ?"
    PET_BY_PARALEGAL = "Select PetitionerID, PetitionerName From Petitioner Where WorkingAttorney IN (Select LegalResourceAttorneyID1 From Project Where LegalResourceStaffID1 = ?) Order BY PetitionerID DESC"
    PET_BY_HR = "Select PetitionerID, PetitionerName From Petitioner Where HRContactID = ?"

    # Get Petitioner Information
    # Overview
    OVERVIEW_PROJECT_FILED = """select REPLACE(YEAR(x.ProjectFiledDate), ',', '') as Year, x.TotalCount    from (Select ProjectFiledDate = DATEADD(YEAR, DATEDIFF(YEAR, 0, ProjectFiledDate), 0), COUNT(*) As 'TotalCount' From[Project], Beneficiary
        Where ProjectFiledDate Between '2015-01-01' AND '2023-12-01' AND[Project].BeneficiaryID = Beneficiary.BeneficiaryID AND Beneficiary.PetitionerID = ? GROUP BY DATEADD(YEAR, DATEDIFF(YEAR, 0, ProjectFiledDate), 0)) x"""
    OVERVIEW_PROJECT_INITIATED = """select REPLACE(YEAR(x.ProjectInitiatedDate), ',', '') as Year, x.TotalCount    from (Select ProjectInitiatedDate = DATEADD(YEAR, DATEDIFF(YEAR, 0, [Project].CreatedDate), 
        0), COUNT(*) As 'TotalCount' From[Project], Beneficiary Where [Project].CreatedDate Between '2015-01-01' AND '2023-12-01' AND[Project].BeneficiaryID = Beneficiary.BeneficiaryID AND Beneficiary.PetitionerID = ? GROUP BY DATEADD(YEAR, DATEDIFF(YEAR, 0, [Project].CreatedDate), 0)) x"""

    # Get Beneficiary By petitioner ID
    TOTAL_BEN_BY_PET = "SELECT COUNT(*) AS 'TotalBeneficiaryCount' FROM Beneficiary WHERE PetitionerID = ?"

    # Incorporation
    INCORPORATION = "Select PetitionerName, TradeNameDBA, YearEstablished, PlaceEstablished, BusinessType, FederalEmployerID, NAICSCode From Petitioner Where PetitionerID = ?"
    # Employee & Revenue
    EMPLOYEE_REVENUE = "Select EmployeeCountUS, EmployeeCountGlobal, AnnualIncomeGrossUS, AnnualIncomeNetUS, AnnualIncomeGrossGlobal, AnnualIncomeNetGlobal From Petitioner Where PetitionerID = ?"
    # Immigration
    IMMIGRATION = "Select BlanketLApprovalNumber, CONVERT(DATE, BlanketLExpirationDate) AS 'BlanketLExpDate', IncludedonCompanyBlanketL, H1BDependentEmployer, PetitionerWillfulViolator, Over50PercentEEsinH1BL1AL1BStatus From Petitioner Where PetitionerID = ?"
    # Total Immigration 
    TOTAL_IMMIGRATION_SPEND = "select REPLACE(x.billingDate, ',', '') as Year, x.BillingAmount    from (Select Sum(BillingAmount) AS 'BillingAmount', Year(BillingDate) AS 'billingDate' From Billing Where PetitionerID = ? Group BY Year(BillingDate)) x"

    # Company Authorized Signatory
    COMPANY_AUTH_SIGN = """Select Contact.FirstName, Contact.LastName, Contact.Email, Petitioner.Phone, Contact.JobTitle From Petitioner, Contact Where Petitioner.AuthorizedSignatory1ContactID = Contact.ContactId 
        AND PetitionerID = ? Union Select Contact.FirstName, Contact.LastName, Contact.Email, Petitioner.Phone, Contact.JobTitle From Petitioner, Contact Where Petitioner.AuthorizedSignatory2ContactID = Contact.ContactId AND PetitionerID = ?"""
    # Company Contact
    COMPANY_CONTACT = "Select Contact.FirstName, Contact.LastName, Contact.Email, Petitioner.Phone, Contact.JobTitle From Petitioner, Contact Where Petitioner.MainCompanyContactID = Contact.ContactId AND PetitionerID = ?"


class DBQueryForBeneficiary:
    # Immigration Timeline
    IMMI_TIMELINE_H1B = "Select Year(ProjectInitiation) AS 'YearInitiated', Year(ProjectFiledDate) AS 'YearFiled', YEAR(ProjectClosedDate) AS 'YearClosed', ProjectPrimaryStatus, ProjectID From [Project] Where ProjectID IN(Select ProjectID From [Project] Where [Project].ProjectPetitionID = 3 AND [Project].ProjectTag1ID = 3 ANd [Project].BeneficiaryID = ? Group BY [Project].CreatedDate, ProjectPetitionID, ProjectID)"
    IMMI_TIMELINE_RECENT_UNDERLYING_NIV_PETITION = """Select Year(ProjectInitiation) AS 'YearInitiated', Year(ProjectFiledDate) AS 'YearFiled', YEAR(ProjectClosedDate) AS 'YearClosed', ProjectPrimaryStatus, ProjectID From [Project] Where ProjectID IN(Select ProjectID From [Project] Where [Project].BeneficiaryID = ? AND [Project].ProjectPetitionID = 2 AND [Project].ProjectTag1ID <> 3 Group BY [Project].CreatedDate, ProjectPetitionID, ProjectID)"""
    IMMI_TIMELINE_RECENT_PERM_APPLICATION = "Select Year(ProjectInitiation) AS 'YearInitiated', Year(ProjectFiledDate) AS 'YearFiled', YEAR(ProjectClosedDate) AS 'YearClosed', ProjectPrimaryStatus, ProjectID From [Project] Where ProjectID IN(Select ProjectID From [Project], Config.PetitionTemplate Where [Project].ProjectPetitionID IN (1 , 12) AND [Project].ProjectPetitionID = Config.PetitionTemplate.PetitionTemplateID AND [Project].BeneficiaryID = ? Group BY [Project].CreatedDate, ProjectPetitionID, ProjectID)"
    IMMI_TIMELINE_RECENT_I140_PETITION = "Select Year(ProjectInitiation) AS 'YearInitiated', Year(ProjectFiledDate) AS 'YearFiled', YEAR(ProjectClosedDate) AS 'YearClosed', ProjectPrimaryStatus, ProjectID From [Project] Where ProjectID IN(Select ProjectID From [Project], Config.PetitionTemplate Where [Project].ProjectPetitionID IN (1, 13) AND [Project].ProjectPetitionID = Config.PetitionTemplate.PetitionTemplateID AND [Project].BeneficiaryID = ? Group BY [Project].CreatedDate, ProjectPetitionID, ProjectID)"
    IMMI_TIMELINE_RECENT_I130_PETITION = "Select Year(ProjectInitiation) AS 'YearInitiated', Year(ProjectFiledDate) AS 'YearFiled', YEAR(ProjectClosedDate) AS 'YearClosed', ProjectPrimaryStatus, ProjectID From [Project] Where ProjectID IN(Select ProjectID From [Project], Config.PetitionTemplate Where [Project].ProjectPetitionID = Config.PetitionTemplate.PetitionTemplateID AND [Project].ProjectPetitionID = 13 AND [Project].BeneficiaryID = ? Group BY [Project].CreatedDate, ProjectPetitionID, ProjectID)"
    IMMI_TIMELINE_RECENT_AOS_APPLICATION = "Select Year(ProjectInitiation) AS 'YearInitiated', Year(ProjectFiledDate) AS 'YearFiled', YEAR(ProjectClosedDate) AS 'YearClosed', ProjectPrimaryStatus, ProjectID From [Project] Where ProjectID IN(Select ProjectID From [Project], Config.PetitionTemplate Where [Project].ProjectPetitionID = Config.PetitionTemplate.PetitionTemplateID AND [Project].ProjectTag3ID = 40 AND [Project].BeneficiaryID = ? Group BY [Project].CreatedDate, ProjectPetitionID, ProjectID)"

    # Work Authorization Info
    WAI_IMMIGRATION = "Select ImmigrationStatusType, CONVERT(DATE, CurrentImmigrationStatusExpirationDate) AS 'StatusExpDate', 'NA' AS 'FutureImmStatusEffectiveDate' From Beneficiary, Config.ImmigrationStatus Where BeneficiaryID = ? AND ImmigrationStatus.ImmigrationStatusID = CurrentImmigrationStatusID"
    WAI_I797 = "Select FOrmClass AS 'CurrentI797Status', CONVERT(DATE, I797ExpirationDate) AS 'CurrentI797ExpirationDate', CONVERT(DATE, DecisionNoticeDate) AS 'DecisionNoticeDate' From Beneficiary, [Project], NoticeDetail Where Beneficiary.BeneficiaryID = ? AND Beneficiary.BeneficiaryID = [Project].BeneficiaryID AND [Project].BeneficiaryID = NoticeDetail.BeneficiaryID AND NoticeDetail.NoticeFormNumber IN ('I-129', 'I-539') AND NoticeDetail.NoticeTypeID = 2 AND NoticeDetail.NoticeClassID = 3 Group BY DecisionNoticeDate, FormClass, I797ExpirationDate Having DecisionNoticeDate = Max(DecisionNoticeDate)"
    WAI_AOS_EAD = "Select Config.DocumentType.DocumentType, CONVERT(DATE, WorkTravelDocument.ValidTo) AS 'ValidTo', CONVERT(DATE, WorkTravelDocument.ValidFrom) AS 'ValidFrom' From WorkTravelDocument, Config.DocumentType Where DATEDIFF(Day, ValidTo, GETDATE()) <= 240 AND WorkTravelDocument.DocumentTypeID = Config.DocumentType.DocumentTypeID AND Config.DocumentType.DocumentType = 'AOS EAD' AND WorkTravelDocument.BeneficiaryID = ?"
    WAI_NIV_EAD = "Select CONVERT(DATE, CurrentNIVEADValidFrom) AS 'CurrentNIVEADValidFrom', CONVERT(DATE, CurrentNIVEADExpirationDate) AS 'CurrentNIVEADValidTo', EADTypeID From Beneficiary Where BeneficiaryID = ? AND EADTypeID IN (Select Config.EADType.EADTypeID From Config.EADType Where EADCategory IN ('NIV'))"

    # PR Process Info
    PR_PROCESS = "Select IsEligiblePRProcess, CONVERT(DATE, PrProcessActualStartDate) AS 'InitiationStartDate', CONVERT(DATE, PrProcessTargetStartDate) AS 'TargetStartDate' From Beneficiary Where BeneficiaryID = ?"
    PR_PERM_Project = "Select CONVERT(DATE, PermProjectFiledDate) AS 'PermProjectFiledDate', PermProjectReceiptNumber, ProjectPrimaryStatus, PermProjectID From Beneficiary, [Project] Where Beneficiary.BeneficiaryID = ? AND Beneficiary.BeneficiaryID = [Project].BeneficiaryID"
    PR_I140 = "Select CONVERT(DATE, I140ProjectFiledDate) AS 'I140ProjectFiledDate', I140ReceiptNumber, ProjectPrimaryStatus, I140ProjectID From Beneficiary, [Project] Where Beneficiary.BeneficiaryID = ? AND Beneficiary.BeneficiaryID = [Project].BeneficiaryID"
    PR_I485 = "Select CONVERT(DATE, AOSProjectFiledDate) AS 'AOSProjectFiledDate', AOSReceiptNumber, ProjectPrimaryStatus, AOSProjectID From Beneficiary, [Project] Where Beneficiary.BeneficiaryID = ? AND Beneficiary.BeneficiaryID = [Project].BeneficiaryID"
    PR_I130 = "Select CONVERT(DATE, I130ProjectFiledDate) AS 'I130ProjectFiledDate', I130ReceiptNumber, ProjectPrimaryStatus, I130ProjectID From Beneficiary, [Project] Where Beneficiary.BeneficiaryID = ? AND Beneficiary.BeneficiaryID = [Project].BeneficiaryID"

    # Priority Info
    PRIO_AOS_FILING_STATUS = "Select CONVERT(DATE, [Project].ProjectFiledDate) AS 'ProjectFiledDate', [Project].ProjectPrimaryStatus, [Project].ProjectSecondaryStatusID, [Project].ProjectPetitionID, [Project].ProjectID From Beneficiary, [Project] Where Beneficiary.BeneficiaryID = ? AND Beneficiary.BeneficiaryID = [Project].BeneficiaryID AND [Project].ProjectPetitionID = (Select PetitionTemplateID From Config.PetitionTemplate Where ProjectPetitionName = 'I-485 Application')"
    PRIO_AOS_FILING_ELIGIBILITY_CURRENT = """Select CONVERT(DATE, ProjectPriorityDate) AS 'ProjectPriorityDate', ProjectPriorityCountry, ProjectPriorityCategory From [Project], Beneficiary, [Config].PetitionTemplate Where [Project].BeneficiaryID = Beneficiary.BeneficiaryID AND [Project].ProjectPetitionID = [Config].PetitionTemplate.PetitionTemplateID  AND Beneficiary.BeneficiaryID = ? AND [Project].ProjectPrimaryStatus IN ('Approved', 'Open') AND ProjectPriorityDate IS NOT NULL AND [Config].PetitionTemplate.ProjectPetitionName NOT IN ('I-140 Petition From Prior Employer') AND [Project].ProjectPetitionID IN (Select [Config].PetitionTemplate.PetitionTemplateID From [Config].PetitionTemplate Where [Config].PetitionTemplate.ProjectPetitionName IN ('I-140 Petition'))
        Union Select CONVERT(DATE, ProjectPriorityDate) AS 'ProjectPriorityDate', ProjectPriorityCountry, ProjectPriorityCategory From [Project], Beneficiary, [Config].PetitionTemplate Where [Project].BeneficiaryID = Beneficiary.BeneficiaryID AND [Project].ProjectPetitionID = [Config].PetitionTemplate.PetitionTemplateID  AND ProjectPriorityDate IS NOT NULL AND Beneficiary.BeneficiaryID = ? AND [Project].ProjectPetitionID IN (Select [Config].PetitionTemplate.PetitionTemplateID From [Config].PetitionTemplate ) GROUP BY ProjectPriorityDate, ProjectPriorityCountry, ProjectPriorityCategory"""
    PRIO_AOS_FILING_ELIGIBILITY_UPCOMING = """Select CONVERT(DATE, ProjectPriorityDate) AS 'ProjectPriorityDate', ProjectPriorityCountry, ProjectPriorityCategory From [Project], Beneficiary, [Config].PetitionTemplate Where [Project].BeneficiaryID = Beneficiary.BeneficiaryID AND [Project].ProjectPetitionID = [Config].PetitionTemplate.PetitionTemplateID  AND Beneficiary.BeneficiaryID = ? AND [Project].ProjectPrimaryStatus IN ('Approved', 'Open') AND [Config].PetitionTemplate.ProjectPetitionName NOT IN ('I-140 Petition From Prior Employer') AND [Project].ProjectPetitionID IN (Select [Config].PetitionTemplate.PetitionTemplateID From [Config].PetitionTemplate Where [Config].PetitionTemplate.ProjectPetitionName IN ('I-140 Petition'))
        Union All Select CONVERT(DATE, ProjectPriorityDate) AS 'ProjectPriorityDate', ProjectPriorityCountry, ProjectPriorityCategory From [Project], Beneficiary, [Config].PetitionTemplate Where [Project].BeneficiaryID = Beneficiary.BeneficiaryID AND [Project].ProjectPetitionID = [Config].PetitionTemplate.PetitionTemplateID  AND Beneficiary.BeneficiaryID = ? AND [Project].ProjectPetitionID IN (Select [Config].PetitionTemplate.PetitionTemplateID From [Config].PetitionTemplate Where [Config].PetitionTemplate.ProjectPetitionName IN ('I-130 Petition'))"""
    PRIORITY_INFO_TABLE = "Select ProjectPetitionName, ISMostRecent, CONVERT(DATE, ProjectPriorityDate) AS 'ProjectPriorityDate', ProjectPriorityCategory, ProjectPriorityCountry, SponserName, UnderlyingPermReceiptNumber, [Project].ReceiptNumber, (Select Petitioner.PetitionerName From Petitioner Where Petitioner.PetitionerID = [Project].PriorEmployerID) AS 'PriorEmployerName', ProjectPrimaryStatus, CONVERT(DATE, [Project].CreatedDate) AS 'CreatedDate', ProjectID From Beneficiary, [Project], Config.PetitionTemplate Where Beneficiary.BeneficiaryID = ? AND Beneficiary.BeneficiaryID = [Project].BeneficiaryID AND [Project].ProjectPetitionID = [Config].PetitionTemplate.PetitionTemplateID AND [Config].PetitionTemplate.ProjectPetitionName IN ('I-140 Petition', 'I-140 Petition From Prior Employer', 'I-130 Petition')"

    # Employment Info
    EMP_INFO_TAB1 = "Select BeneficiaryEmployment.EmployerName, BeneficiaryEmployment.EmployeeId, BeneficiaryEmployment.JobTitle From Beneficiary, BeneficiaryEmployment Where Beneficiary.BeneficiaryID = BeneficiaryEmployment.BeneficiaryID AND Beneficiary.BeneficiaryID = ? AND IsCurrent = 'True'"
    EMP_INFO_TAB2 = "Select 'NA' AS 'WorksATMultipleSites', 'NA' AS 'PrimaryWorkLocation', 'NA' AS 'AdditionalWorkLocations' From Beneficiary, BeneficiaryEmployment Where Beneficiary.BeneficiaryID = BeneficiaryEmployment.BeneficiaryID AND Beneficiary.BeneficiaryID = ? AND IsCurrent = 'True'"
    EMP_INFO_TAB3 = "Select CONVERT(DATE, BeneficiaryEmployment.HireDate) AS 'HireDate', 'NA' AS 'MostRecentLCANumber' From Beneficiary, BeneficiaryEmployment Where Beneficiary.BeneficiaryID = BeneficiaryEmployment.BeneficiaryID AND Beneficiary.BeneficiaryID = ? AND IsCurrent = 'True'"

    # Passport & Travel
    PT_MOST_RECENT_TRAVEL = "Select CONVERT(DATE, TravelStartDate) AS 'TravelStartDate', TravelType From Beneficiary, BeneficiaryTravel Where Beneficiary.BeneficiaryID = BeneficiaryTravel.BeneficiaryID AND Beneficiary.BeneficiaryID = ? Order BY TravelStartDate DESC"
    PT_PASSPORT = "Select BeneficiaryPassport.IssuenceCountry, BeneficiaryPassport.PassportNumber, CONVERT(DATE, BeneficiaryPassport.ValidTo) AS 'ValidTo' From BeneficiaryPassport, Beneficiary Where BeneficiaryPassport.BeneficiaryID = Beneficiary.BeneficiaryID AND BeneficiaryPassport.BeneficiaryID = ?"
    PT_VISA = "Select BeneficiaryVisa.VisaType, CONVERT(DATE, BeneficiaryVisa.ValidTo) AS 'ValidTo', (Select Config.VisaClass.VisaClass From Config.VisaClass Where Config.VisaClass.VisaClassID = BeneficiaryVisa.VisaClassID) AS 'VisaClass', (Select Config.VisaCategory.VisaCategory From Config.VisaCategory Where Config.VisaCategory.VisaCategoryID = BeneficiaryVisa.VisaCategoryID) AS 'VisaCategory' From BeneficiaryVisa, Beneficiary Where BeneficiaryVisa.BeneficiaryID = Beneficiary.BeneficiaryID AND BeneficiaryVisa.BeneficiaryID = ? AND IsCurrent = 'True'"
    PT_TRAVEL_DOCUMENT = "Select TravelDocumentUsed, CONVERT(DATE, I94ExpirationDate) AS 'I94ExpirationDate' From Beneficiary, BeneficiaryTravel Where Beneficiary.BeneficiaryID = BeneficiaryTravel.BeneficiaryID AND Beneficiary.BeneficiaryID = ? Order BY TravelStartDate DESC"
    PT_UPCOMING_TRAVEL = "Select CONVERT(DATE, TentativeDepartureDate) AS 'TentativeDepartureDate', CONVERT(DATE, TentativeArrivalDate) AS 'TentativeArrivalDate' From Beneficiary, BeneficiaryTravel Where Beneficiary.BeneficiaryID = BeneficiaryTravel.BeneficiaryID AND Beneficiary.BeneficiaryID = ? Order BY TravelStartDate DESC"

    # Personal Info
    PI_BIRTH_INFO = "Select CONVERT(DATE, BirthDate) AS 'BirthDate', BirthCity, BirthStateProvince, BirthCountry From Beneficiary Where BeneficiaryID = ?"
    PI_CITIZENSHIP = "Select CitizenshipCountry, PermPriorityCountry, AllCitizenshipCountries From Beneficiary Where BeneficiaryID = ?"
    PI_MARITAL_STATUS = "Select Beneficiary.MaritalStatus, CONVERT(DATE, BeneficiaryMaritalInfo.MarriageDate) AS 'MarriageDate', BeneficiaryMaritalInfo.DateofDivorce, (Select Count(*) - 1 From Beneficiary Where Beneficiary.PrimaryBeneficiaryID = ?) AS 'NumberofDependents' From Beneficiary, BeneficiaryMaritalInfo Where BeneficiaryMaritalInfo.BeneficiaryID = ? AND BeneficiaryMaritalInfo.BeneficiaryID = Beneficiary.BeneficiaryID Group BY Beneficiary.MaritalStatus, BeneficiaryMaritalInfo.MarriageDate, BeneficiaryMaritalInfo.DateofDivorce"
    PI_CONTACT_INFO = "Select WorkEmail, PersonalEmail, HomePhone, WorkPhone, Mobile From Beneficiary Where BeneficiaryID = ?"

    # IMMIGRATION STATUS & KEY DATES 
    ISK_IMMIGRATION_INFO = "Select ImmigrationStatusType, CONVERT(DATE, CurrentImmigrationStatusExpirationDate) AS 'StatusExpDate', 'NA' AS 'FutureImmStatusEffectiveDate' From Beneficiary, Config.ImmigrationStatus Where BeneficiaryID = ? AND ImmigrationStatus.ImmigrationStatusID = CurrentImmigrationStatusID"
    ISK_I_797_INFO = "Select FOrmClass AS 'CurrentI797Status', CONVERT(DATE, I797ExpirationDate) AS 'CurrentI797ExpirationDate', CONVERT(DATE, DecisionNoticeDate) AS 'DecisionNoticeDate' From Beneficiary, [Project], NoticeDetail Where Beneficiary.BeneficiaryID = ? AND Beneficiary.BeneficiaryID = [Project].BeneficiaryID AND [Project].BeneficiaryID = NoticeDetail.BeneficiaryID AND NoticeDetail.NoticeFormNumber IN ('I-129', 'I-539') AND NoticeDetail.NoticeTypeID = 2 AND NoticeDetail.NoticeClassID = 3 Group BY DecisionNoticeDate, FormClass, I797ExpirationDate Having DecisionNoticeDate = Max(DecisionNoticeDate)"
    ISK_I_129S_INFO = "Select FormClass AS 'CurrentI797Status', CONVERT(DATE, I797ExpirationDate) AS 'CurrentI797ExpirationDate', CONVERT(DATE, DecisionNoticeDate) AS 'DecisionNoticeDate' From Beneficiary, [Project], NoticeDetail Where Beneficiary.BeneficiaryID = ? AND Beneficiary.BeneficiaryID = [Project].BeneficiaryID AND [Project].BeneficiaryID = NoticeDetail.BeneficiaryID AND NoticeDetail.NoticeFormNumber IN ('I-129', 'I-539') AND NoticeDetail.NoticeTypeID = 2 AND NoticeDetail.NoticeClassID = 3 Group BY DecisionNoticeDate, FormClass, I797ExpirationDate Having DecisionNoticeDate = Max(DecisionNoticeDate)"
    ISK_US_ENTRY_INFO = "Select CONVERT(DATE, EntryDate) AS 'RecentEntryDate', I94Number From Beneficiary, BeneficiaryTravel Where Beneficiary.BeneficiaryID =BeneficiaryTravel.BeneficiaryID AND BeneficiaryTravel.EntryMostRecent = 'True' AND TravelType = 'Arrival' Group BY EntryDate, I94Number Having Max(EntryDate) = EntryDate"
    ISK_VISA_INFO = "Select VisaClass, CONVERT(DATE, ValidTo) AS 'ValidTo', CONVERT(DATE, VisaPedDate) AS 'VisaPedDate' From Beneficiary, BeneficiaryVisa, Config.VisaClass Where Beneficiary.BeneficiaryID =BeneficiaryVisa.BeneficiaryID AND BeneficiaryVisa.IsCurrent = 'True' AND BeneficiaryVisa.VisaClassID IN (Select VisaClass.VisaClassID From Config.VisaClass) AND Beneficiary.BeneficiaryID = ? AND BeneficiaryVisa.VisaClassID = Config.VisaClass.VisaClassID Group BY VisaClass, ValidTo, VisaPedDate"
    ISK_PR_INFO = "Select CONVERT(DATE, ReEntryPermitExpirationDate) AS 'PermitExpDate', CONVERT(DATE, GreenCardExpirationDate) AS 'GreenCardExpDate' From Beneficiary, [Project], NoticeDetail Where Beneficiary.BeneficiaryID = ? AND Beneficiary.BeneficiaryID = [Project].BeneficiaryID AND [Project].BeneficiaryID = NoticeDetail.BeneficiaryID AND NoticeDetail.NoticeFormNumber IN ('I-129', 'I-539') AND NoticeDetail.NoticeTypeID = 2 AND NoticeDetail.NoticeClassID = 3 Group BY DecisionNoticeDate, ReEntryPermitExpirationDate, GreenCardExpirationDate Having DecisionNoticeDate = Max(DecisionNoticeDate)"

    # Quick Assessment
    QA_NIV = """Select Config.DocumentType.DocumentType, CONVERT(DATE, WorkTravelDocument.ValidTo) AS 'ExpDate', 
        (Select 'Yes' From Project Where Project.BeneficiaryID = WorkTravelDocument.BeneficiaryID AND ProjectPetitionID IN (2, 7, 8, 9, 10, 11) AND ProjectTag1ID IN (1, 2, 6, 7, 8) AND ProjectTag3ID IN (21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39)) AS 'ExtRenInitiated', 
        (Select CONVERT(DATE, CreatedDate) From Project Where Project.BeneficiaryID = WorkTravelDocument.BeneficiaryID AND ProjectPetitionID IN (2, 7, 8, 9, 10, 11) AND ProjectTag1ID IN (1, 2, 6, 7, 8) AND ProjectTag3ID IN (21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39)) AS 'ProjectInitiatedDate', 
        (Select Config.SecondaryProjectStatus.SecondaryProjectStatusType From Project, Config.SecondaryProjectStatus Where Project.BeneficiaryID = WorkTravelDocument.BeneficiaryID AND ProjectPetitionID IN (2, 7, 8, 9, 10, 11) AND ProjectTag1ID IN (1, 2, 6, 7, 8) AND Project.ProjectSecondaryStatusID = Config.SecondaryProjectStatus.SecondaryProjectStatusID AND ProjectTag3ID IN (21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39)) AS 'SecondaryProjectStatus', 
        (Select ProjectID From Project Where Project.BeneficiaryID = WorkTravelDocument.BeneficiaryID AND ProjectPetitionID IN (2, 7, 8, 9, 10, 11) AND ProjectTag1ID IN (1, 2, 6, 7, 8) AND ProjectTag3ID IN (21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39)) AS 'ProjectID' 
        From WorkTravelDocument, Config.DocumentType Where DATEDIFF(Day, ValidTo, GETDATE()) <= 240 AND WorkTravelDocument.DocumentTypeID = Config.DocumentType.DocumentTypeID AND Config.DocumentType.DocumentType = 'NIV Status' AND WorkTravelDocument.BeneficiaryID = ?"""
    QA_NIV_EAD = """Select Config.DocumentType.DocumentType, CONVERT(DATE, WorkTravelDocument.ValidTo) AS 'ExpDate', 
        (Select 'Yes' From Project Where Project.BeneficiaryID = WorkTravelDocument.BeneficiaryID AND ProjectPetitionID IN (17) AND ProjectTag1ID IN (6, 11) AND ProjectTag3ID IN (41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55)) AS 'ExtRenInitiated', 
        (Select CONVERT(DATE, CreatedDate) From Project Where Project.BeneficiaryID = WorkTravelDocument.BeneficiaryID AND ProjectPetitionID IN (17) AND ProjectTag1ID IN (6, 11) AND ProjectTag3ID IN (41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55)) AS 'ProjectInitiatedDate', 
        (Select Config.SecondaryProjectStatus.SecondaryProjectStatusType From Project, Config.SecondaryProjectStatus Where Project.BeneficiaryID = WorkTravelDocument.BeneficiaryID AND ProjectPetitionID IN (17) AND ProjectTag1ID IN (6, 11) AND Project.ProjectSecondaryStatusID = Config.SecondaryProjectStatus.SecondaryProjectStatusID AND ProjectTag3ID IN (41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55)) AS 'SecondaryProjectStatus', 
        (Select ProjectID From Project Where Project.BeneficiaryID = WorkTravelDocument.BeneficiaryID AND ProjectPetitionID IN (17) AND ProjectTag1ID IN (6, 11) AND ProjectTag3ID IN (41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55)) AS 'ProjectID' 
        From WorkTravelDocument, Config.DocumentType Where DATEDIFF(Day, ValidTo, GETDATE()) <= 240 AND WorkTravelDocument.DocumentTypeID = Config.DocumentType.DocumentTypeID AND Config.DocumentType.DocumentType = 'EAD' AND WorkTravelDocument.BeneficiaryID = ?"""
    QA_AOS_EAD = """Select Config.DocumentType.DocumentType, CONVERT(DATE, WorkTravelDocument.ValidTo) AS 'ExpDate',
        (Select 'Yes' From Project Where Project.BeneficiaryID = WorkTravelDocument.BeneficiaryID AND ProjectPetitionID IN (17) AND ProjectTag1ID IN (6, 11) AND ProjectTag3ID IN (40)) AS 'ExtRenInitiated', 
        (Select CONVERT(DATE, CreatedDate) From Project Where Project.BeneficiaryID = WorkTravelDocument.BeneficiaryID AND ProjectPetitionID IN (17) AND ProjectTag1ID IN (6, 11) AND ProjectTag3ID IN (402)) AS 'ProjectInitiatedDate', 
        (Select Config.SecondaryProjectStatus.SecondaryProjectStatusType From Project, Config.SecondaryProjectStatus Where Project.BeneficiaryID = WorkTravelDocument.BeneficiaryID AND ProjectPetitionID IN (17) AND ProjectTag1ID IN (6, 11) AND Project.ProjectSecondaryStatusID = Config.SecondaryProjectStatus.SecondaryProjectStatusID AND ProjectTag3ID IN (40)) AS 'SecondaryProjectStatus', 
        (Select ProjectID From Project Where Project.BeneficiaryID = WorkTravelDocument.BeneficiaryID AND ProjectPetitionID IN (17) AND ProjectTag1ID IN (6, 11) AND ProjectTag3ID IN (40)) AS 'ProjectID' 
        From WorkTravelDocument, Config.DocumentType Where DATEDIFF(Day, ValidTo, GETDATE()) <= 240 AND WorkTravelDocument.DocumentTypeID = Config.DocumentType.DocumentTypeID AND Config.DocumentType.DocumentType = 'AOS EAD' AND WorkTravelDocument.BeneficiaryID = ?"""
    QA_ADVANCE_PAROL = """Select Config.DocumentType.DocumentType, CONVERT(DATE, WorkTravelDocument.ValidTo) AS 'ExpDate', 
        (Select 'Yes' From Project Where Project.BeneficiaryID = WorkTravelDocument.BeneficiaryID AND ProjectPetitionID IN (18) AND ProjectTag1ID IN (6, 11) AND ProjectTag3ID IN (72)) AS 'ExtRenInitiated', 
        (Select CONVERT(DATE, CreatedDate) From Project Where Project.BeneficiaryID = WorkTravelDocument.BeneficiaryID AND ProjectPetitionID IN (18) AND ProjectTag1ID IN (6, 11) AND ProjectTag3ID IN (72)) AS 'ProjectInitiatedDate',
        (Select Config.SecondaryProjectStatus.SecondaryProjectStatusType From Project, Config.SecondaryProjectStatus Where Project.BeneficiaryID = WorkTravelDocument.BeneficiaryID AND ProjectPetitionID IN (18) AND ProjectTag1ID IN (6, 11) AND Project.ProjectSecondaryStatusID = Config.SecondaryProjectStatus.SecondaryProjectStatusID AND ProjectTag3ID IN (72)) AS 'SecondaryProjectStatus', 
        (Select ProjectID From Project Where Project.BeneficiaryID = WorkTravelDocument.BeneficiaryID AND ProjectPetitionID IN (18) AND ProjectTag1ID IN (6, 11) AND ProjectTag3ID IN (72)) AS 'ProjectID' 
        From WorkTravelDocument, Config.DocumentType Where DATEDIFF(Day, ValidTo, GETDATE()) <= 240 AND WorkTravelDocument.DocumentTypeID = Config.DocumentType.DocumentTypeID AND Config.DocumentType.DocumentType = 'Advance Parole' AND WorkTravelDocument.BeneficiaryID = ?"""
    QA_RE_ENTRY_PERMIT = """Select Config.DocumentType.DocumentType, CONVERT(DATE, WorkTravelDocument.ValidTo) AS 'ExpDate', 
        (Select 'Yes' From Project Where Project.BeneficiaryID = WorkTravelDocument.BeneficiaryID AND ProjectPetitionID IN (18) AND ProjectTag1ID IN (6, 11) AND ProjectTag3ID IN (73)) AS 'ExtRenInitiated', 
        (Select CONVERT(DATE, CreatedDate) From Project Where Project.BeneficiaryID = WorkTravelDocument.BeneficiaryID AND ProjectPetitionID IN (18) AND ProjectTag1ID IN (6, 11) AND ProjectTag3ID IN (73)) AS 'ProjectInitiatedDate', 
        (Select Config.SecondaryProjectStatus.SecondaryProjectStatusType From Project, Config.SecondaryProjectStatus Where Project.BeneficiaryID = WorkTravelDocument.BeneficiaryID AND ProjectPetitionID IN (18) AND ProjectTag1ID IN (6, 11) AND Project.ProjectSecondaryStatusID = Config.SecondaryProjectStatus.SecondaryProjectStatusID AND ProjectTag3ID IN (73)) AS 'SecondaryProjectStatus', 
        (Select ProjectID From Project Where Project.BeneficiaryID = WorkTravelDocument.BeneficiaryID AND ProjectPetitionID IN (18) AND ProjectTag1ID IN (6, 11) AND ProjectTag3ID IN (73)) AS 'ProjectID' 
        From WorkTravelDocument, Config.DocumentType Where DATEDIFF(Day, ValidTo, GETDATE()) <= 240 AND WorkTravelDocument.DocumentTypeID = Config.DocumentType.DocumentTypeID AND Config.DocumentType.DocumentType = 'Re-Entry Permit' AND WorkTravelDocument.BeneficiaryID = ?"""
    QA_GREEN_CARD = """Select Config.DocumentType.DocumentType, CONVERT(DATE, WorkTravelDocument.ValidTo) AS 'ExpDate', 
        (Select 'Yes' From Project Where Project.BeneficiaryID = WorkTravelDocument.BeneficiaryID AND ProjectPetitionID IN (19) AND ProjectTag1ID IN (6, 11)) AS 'ExtRenInitiated', 
        (Select CONVERT(DATE, CreatedDate) From Project Where Project.BeneficiaryID = WorkTravelDocument.BeneficiaryID AND ProjectPetitionID IN (19) AND ProjectTag1ID IN (6, 11)) AS 'ProjectInitiatedDate', 
        (Select Config.SecondaryProjectStatus.SecondaryProjectStatusType From Project, Config.SecondaryProjectStatus Where Project.BeneficiaryID = WorkTravelDocument.BeneficiaryID AND ProjectPetitionID IN (19) AND ProjectTag1ID IN (6, 11) AND Project.ProjectSecondaryStatusID = Config.SecondaryProjectStatus.SecondaryProjectStatusID) AS 'SecondaryProjectStatus', 
        (Select ProjectID From Project Where Project.BeneficiaryID = WorkTravelDocument.BeneficiaryID AND ProjectPetitionID IN (19) AND ProjectTag1ID IN (6, 11)) AS 'ProjectID' 
        From WorkTravelDocument, Config.DocumentType Where DATEDIFF(Day, ValidTo, GETDATE()) <= 240 AND WorkTravelDocument.DocumentTypeID = Config.DocumentType.DocumentTypeID AND Config.DocumentType.DocumentType = 'Green Card' AND WorkTravelDocument.BeneficiaryID = ?"""
    
    QA_IMMIGRATION = "Select ImmigrationStatusType, CONVERT(DATE, CurrentImmigrationStatusExpirationDate) AS 'StatusExpDate', 'NA' AS 'FutureImmStatusEffectiveDate' From Beneficiary, Config.ImmigrationStatus Where BeneficiaryID = ? AND ImmigrationStatus.ImmigrationStatusID = CurrentImmigrationStatusID"
    QA_FORM_I_797 = "Select FormClass AS 'CurrentI797Status', CONVERT(DATE, I797ExpirationDate) AS 'CurrentI797ExpirationDate', CONVERT(DATE, DecisionNoticeDate) AS 'DecisionNoticeDate' From Beneficiary, [Project], NoticeDetail Where Beneficiary.BeneficiaryID = ? AND Beneficiary.BeneficiaryID = [Project].BeneficiaryID AND [Project].BeneficiaryID = NoticeDetail.BeneficiaryID AND NoticeDetail.NoticeFormNumber IN ('I-129', 'I-539') AND NoticeDetail.NoticeTypeID = 2 AND NoticeDetail.NoticeClassID = 3 Group BY DecisionNoticeDate, FormClass, I797ExpirationDate Having DecisionNoticeDate = Max(DecisionNoticeDate)"
    QA_FORM_I_129S = "Select FormClass AS 'CurrentI797Status', CONVERT(DATE, I797ExpirationDate) AS 'CurrentI797ExpirationDate', CONVERT(DATE, DecisionNoticeDate) AS 'DecisionNoticeDate' From Beneficiary, [Project], NoticeDetail Where Beneficiary.BeneficiaryID = ? AND Beneficiary.BeneficiaryID = [Project].BeneficiaryID AND [Project].BeneficiaryID = NoticeDetail.BeneficiaryID AND NoticeDetail.NoticeFormNumber IN ('I-129', 'I-539') AND NoticeDetail.NoticeTypeID = 2 AND NoticeDetail.NoticeClassID = 3 Group BY DecisionNoticeDate, FormClass, I797ExpirationDate Having DecisionNoticeDate = Max(DecisionNoticeDate)"
    QA_US_ENTRY = "Select CONVERT(DATE, EntryDate) AS 'RecentEntryDate', I94Number From Beneficiary, BeneficiaryTravel Where Beneficiary.BeneficiaryID = BeneficiaryTravel.BeneficiaryID AND BeneficiaryTravel.EntryMostRecent = 'True' AND TravelType = 'Arrival' Group BY EntryDate, I94Number Having Max(EntryDate) = EntryDate"
    QA_VISA = "Select VisaClass, CONVERT(DATE, ValidTo) AS 'ValidTo', CONVERT(DATE, VisaPedDate) AS 'VisaPedDate' From Beneficiary, BeneficiaryVisa, Config.VisaClass Where Beneficiary.BeneficiaryID =BeneficiaryVisa.BeneficiaryID AND BeneficiaryVisa.IsCurrent = 'True' AND BeneficiaryVisa.VisaClassID IN (Select VisaClass.VisaClassID From Config.VisaClass) AND Beneficiary.BeneficiaryID = ? AND BeneficiaryVisa.VisaClassID = Config.VisaClass.VisaClassID Group BY VisaClass, ValidTo, VisaPedDate"
    QA_PR_DATA = "Select CONVERT(DATE, ReEntryPermitExpirationDate) AS 'PermitExpDate', CONVERT(DATE, GreenCardExpirationDate) AS 'GreenCardExpDate' From Beneficiary, [Project], NoticeDetail Where Beneficiary.BeneficiaryID = ? AND Beneficiary.BeneficiaryID = [Project].BeneficiaryID AND [Project].BeneficiaryID = NoticeDetail.BeneficiaryID AND NoticeDetail.NoticeFormNumber IN ('I-129', 'I-539') AND NoticeDetail.NoticeTypeID = 2 AND NoticeDetail.NoticeClassID = 3 Group BY DecisionNoticeDate, ReEntryPermitExpirationDate, GreenCardExpirationDate Having DecisionNoticeDate = Max(DecisionNoticeDate)"
    QA_OTHER_1 = "Select CONVERT(DATE, InitialHlEntryDate) AS 'FinalNIVInitialHLEntry', CONVERT(DATE, Ds2019ExpirationDate) AS 'Ds2019ExpirationDate', CONVERT(DATE, FinalNivDate) AS 'NIVMaxOutDate', CONVERT(DATE, IIF(FifthYearEndDate IS NULL, (Select DATEADD(DAY, -1, DATEADD(Year, 5, InitialHlEntryDate))  From Beneficiary Where CurrentImmigrationStatusID In ('35', '36') AND InitialHlEntryDate IS NOT NULL AND BeneficiaryID = ?) , FifthYearEndDate))  AS 'FifthYearExp' From Beneficiary Where BeneficiaryID = ?"
    QA_OTHER_2 = "Select SubjectToHomeStayRequirement, CONVERT(DATE, HomeStayRequirementComplied) AS 'HomeStayRequirementComplied', CONVERT(DATE, HomeStayWaiverObtain) AS 'HomeStayWaiverObtain' From Beneficiary, BeneficiaryVisa Where Beneficiary.BeneficiaryID = BeneficiaryVisa.BeneficiaryID AND BeneficiaryVisa.VisaClassID IN (17, 18) AND Beneficiary.BeneficiaryID = ? AND HasPreviouslyHeldJVisaStatus = 'True'"
    QA_BEN_DETAILS = "Select Beneficiary.BeneficiaryID, BeneficiaryEmployment.EmployeeId, Beneficiary.FirstName, Beneficiary.LastName, BeneficiaryEmployment.EmployerName From Beneficiary, BeneficiaryEmployment Where Beneficiary.BeneficiaryID = BeneficiaryEmployment.BeneficiaryID AND Beneficiary.BeneficiaryID = ?"
    BEN_SEARCH_BY_NAME = "Select BeneficiaryID, BeneficiaryXref, FirstName, MiddleName, LastName From Beneficiary Where FirstName Like ? OR MiddleName Like ? OR LastName Like ? Group BY BeneficiaryXref, FirstName, MiddleName, LastName, BeneficiaryID"
    BEN_SEARCH_FULL = "Select BeneficiaryID, BeneficiaryXref, FirstName, MiddleName, LastName From Beneficiary Where FirstName Like ? OR MiddleName Like ? OR LastName Like ? OR BirthDate = ? OR I140ProjectID = ? OR PetitionerID = ? Group BY BeneficiaryXref, FirstName, MiddleName, LastName, BeneficiaryID"
    BEN_SEARCH_BY_NAME_BDATE_PRJID = "Select BeneficiaryID, BeneficiaryXref, FirstName, MiddleName, LastName From Beneficiary Where FirstName Like ? OR MiddleName Like ? OR LastName Like ? AND BirthDate = ? AND I140ProjectID = ? Group BY BeneficiaryXref, FirstName, MiddleName, LastName, BeneficiaryID"
    BEN_SEARCH_BY_NAME_BDATE_PETID = "Select BeneficiaryID, BeneficiaryXref, FirstName, MiddleName, LastName From Beneficiary Where FirstName Like ? OR MiddleName Like ? OR LastName Like ? AND BirthDate = ? AND PetitionerID = ? Group BY BeneficiaryXref, FirstName, MiddleName, LastName, BeneficiaryID"
    BEN_SEARCH_BY_NAME_PRJID_PETID = "Select BeneficiaryID, BeneficiaryXref, FirstName, MiddleName, LastName From Beneficiary Where FirstName Like ? OR MiddleName Like ? OR LastName Like ? AND I140ProjectID = ? AND PetitionerID = ? Group BY BeneficiaryXref, FirstName, MiddleName, LastName, BeneficiaryID"
    BEN_SEARCH_BY_NAME_BDATE = "Select BeneficiaryID, BeneficiaryXref, FirstName, MiddleName, LastName From Beneficiary Where FirstName Like ? OR MiddleName Like ? OR LastName Like ? AND BirthDate = ? Group BY BeneficiaryXref, FirstName, MiddleName, LastName, BeneficiaryID"
    BEN_SEARCH_BY_NAME_PRJID = "Select BeneficiaryID, BeneficiaryXref, FirstName, MiddleName, LastName From Beneficiary Where FirstName Like ? OR MiddleName Like ? OR LastName Like ? AND I140ProjectID = ? Group BY BeneficiaryXref, FirstName, MiddleName, LastName, BeneficiaryID"
    BEN_SEARCH_BY_NAME_PetID = "Select BeneficiaryID, BeneficiaryXref, FirstName, MiddleName, LastName From Beneficiary Where FirstName Like ? OR MiddleName Like ? OR LastName Like ? AND PetitionerID = ? Group BY BeneficiaryXref, FirstName, MiddleName, LastName, BeneficiaryID"