import CustomTile from 'components/Common/CustomTile'
import { Badge, Button, Card, Col, Dropdown, ListGroup, Row } from 'react-bootstrap'
import { Permission } from 'components/Common/Permission'
import { v4 as uuidv4 } from 'uuid'
import { Line } from 'react-chartjs-2'
import * as edashboard from './GraphData'
import { ATTORNEY, BENEFICIARY, PARALEGAL } from 'config/constants'

const OverviewTiles = ({ totalProjects, petitioner, beneficiary }) => {
    const _totalProjects = {
        columns: [
            {
                title: 'Total Projects',
                description: 'Last Calendar Month',
                labels: ['Firm', 'My'],
                values: [totalProjects.total_firm_projects, totalProjects.total_my_projects]
            }
        ]
    }

    const _petitioner = {
        columns: [
            {
                title: 'Total Petitioner',
                description: '',
                labels: ['Firm', 'My'],
                values: [petitioner.total_firm_petitioner, petitioner.total_my_petitioner]
            },
            {
                title: 'Total New Petitioner',
                description: '',
                labels: ['Firm', 'My'],
                values: [petitioner.total_new_firm_petitioner, petitioner.total_new_my_petitioner]
            }
        ]
    }

    const _beneficiary = {
        columns: [
            {
                title: 'Total Beneficiary',
                description: '',
                labels: ['Firm', 'My'],
                values: [beneficiary.total_firm_beneficiary, beneficiary.total_my_beneficiary]
            },
            {
                title: 'Total New Beneficiary',
                description: '',
                labels: ['Firm', 'My'],
                values: [beneficiary.total_new_firm_beneficiary, beneficiary.total_new_my_beneficiary]
            }
        ]
    }

    return (
        <Col sm={12} lg={12} xl={12}>
            <Row className="grid-containerx draggable-area row-sm">
                <Permission disallowedRoles={[BENEFICIARY]}>
                    <Col className="box1 editable" sm={12} md={3} lg={3} xl={2}>
                        <CustomTile initialState={_totalProjects} />
                    </Col>
                </Permission>

                <Permission allowedRoles={[ATTORNEY, PARALEGAL]}>
                    <Col className="box2 editable" sm={12} md={6} lg={6} xl={5}>
                        <CustomTile initialState={_petitioner} />
                    </Col>
                </Permission>

                <Permission allowedRoles={[ATTORNEY, PARALEGAL, BENEFICIARY]}>
                    <Col className="box3 editable" sm={12} md={6} lg={6} xl={5}>
                        <CustomTile initialState={_beneficiary} />
                    </Col>
                </Permission>
            </Row>
        </Col>
    )
}

const CaseGraphs = ({ graphsData }) => {
    return (
        <Col xl={12} lg={12} md={12} className="mb-0">
            <Row>
                <Permission allowedRoles={[ATTORNEY, PARALEGAL]}>
                    <Col xxl={6} xl={12} lg={12} md={12}>
                        <Card className="custom-card">
                            <Card.Header className=" border-bottom-0">
                                <div className="d-flex justify-content-between">
                                    <div>
                                        <label className="main-content-label my-auto pt-2">Project Filed</label>
                                        <span className="d-block tx-12 mb-0 mt-1 text-muted">
                                            Revenue is the total amount of income generated by the sale of goods.
                                        </span>
                                    </div>
                                    <Dropdown>
                                        <Dropdown.Toggle variant="primary" size="sm">
                                            Compare
                                            <i className="fas fa-caret-down ms-1"></i>
                                        </Dropdown.Toggle>
                                        <Dropdown.Menu style={{ marginTop: '0px' }}>
                                            <Dropdown.Item href="#/action-1">Previous Filed</Dropdown.Item>
                                            <Dropdown.Item href="#/action-1">Current Filed</Dropdown.Item>
                                        </Dropdown.Menu>
                                    </Dropdown>
                                </div>
                            </Card.Header>
                            <Card.Body style={{ paddingTop: 0 }}>
                                <div className="chart-wrapperchart-dropshadow2 ht-300">
                                    <Line
                                        options={edashboard.caseFiledOptions}
                                        data={edashboard.loadFiledData(graphsData?.filed)}
                                        className="barchart chart-dropshadow2 ht-300 chartjs-render-monitor"
                                        height="100"
                                    />
                                </div>
                            </Card.Body>
                        </Card>
                    </Col>
                </Permission>
                <Permission allowedRoles={[ATTORNEY, PARALEGAL]}>
                    <Col xxl={6} xl={12} lg={12} md={12}>
                        <Card className="custom-card">
                            <Card.Header className=" border-bottom-0">
                                <div className="d-flex justify-content-between">
                                    <div>
                                        <label className="main-content-label my-auto pt-2">Project Initiated</label>
                                        <span className="d-block tx-12 mb-0 mt-1 text-muted">
                                            Revenue is the total amount of income generated by the sale of goods.
                                        </span>
                                    </div>
                                    <Dropdown>
                                        <Dropdown.Toggle variant="info" size="sm">
                                            Compare
                                            <i className="fas fa-caret-down ms-1"></i>
                                        </Dropdown.Toggle>
                                        <Dropdown.Menu style={{ marginTop: '0px' }}>
                                            <Dropdown.Item href="#/action-1">Previous Initiated</Dropdown.Item>
                                            <Dropdown.Item href="#/action-1">Current Initiated</Dropdown.Item>
                                        </Dropdown.Menu>
                                    </Dropdown>
                                </div>
                            </Card.Header>
                            <Card.Body style={{ paddingTop: 0 }}>
                                <div className="chart-wrapperchart-dropshadow2 ht-300">
                                    <Line
                                        options={edashboard.caseInitiatedOptions}
                                        data={edashboard.loadInitiatedData(graphsData?.initiated)}
                                        className="barchart chart-dropshadow2 ht-300 chartjs-render-monitor"
                                        height="100"
                                    />
                                </div>
                            </Card.Body>
                        </Card>
                    </Col>
                </Permission>
            </Row>
        </Col>
    )
}

const OpenCasesListView = ({ paralegalProjects }) => {
    paralegalProjects = paralegalProjects || []

    let sumValue = paralegalProjects?.map((e) => e.CountOFProject)

    if (sumValue.length) sumValue = sumValue.reduce((a, b) => a + b)

    return (
        <Col xl={3} md={12} sm={12}>
            <Card className="custom-card">
                <Card.Body className="dashboard-recent-cases">
                    <div className="d-flex justify-content-between align-items-center">
                        <div>
                            <h5 className="main-content-label m-0">
                                OPEN PROJECTS BY PARALEGAL
                                <Badge pill bg="primary" className="ms-2">
                                    {sumValue}
                                </Badge>
                            </h5>
                        </div>
                    </div>
                    <ListGroup className="task-list-group mt-3">
                        {paralegalProjects.map((item) => {
                            return (
                                <ListGroup.Item action className="flex-column align-items-start p-3" key={uuidv4()}>
                                    <div className="d-flex w-100 justify-content-between">
                                        <h6 className="font-weight-semibold">
                                            {`${item.FirstName} ${item.LastName}`}: {item.CountOFProject}
                                        </h6>
                                    </div>
                                </ListGroup.Item>
                            )
                        })}
                    </ListGroup>
                </Card.Body>
            </Card>
        </Col>
    )
}

const CustomTileView = () => {
    return (
        <Row className="row-sm">
            <Permission allowedRoles={[ATTORNEY, PARALEGAL]}>
                <Col md={6} sm={6} xl={3}>
                    <Card className="custom-card">
                        <Card.Body className="text-center">
                            <div className="icon-service bg-primary-transparent rounded-circle text-primary">
                                <i className="fe fe-user"></i>
                            </div>
                            <p className="mb-1 text-muted">Custom Label 1</p>
                            <h3 className="mb-0">0</h3>
                        </Card.Body>
                    </Card>
                </Col>
            </Permission>
            <Permission allowedRoles={[ATTORNEY, PARALEGAL]}>
                <Col md={6} sm={6} xl={3}>
                    <Card className="custom-card">
                        <Card.Body className="text-center">
                            <div className="icon-service bg-primary-transparent rounded-circle text-primary">
                                <i className="fe fe-user"></i>
                            </div>
                            <p className="mb-1 text-muted">Custom Label 2</p>
                            <h3 className="mb-0">0</h3>
                        </Card.Body>
                    </Card>
                </Col>
            </Permission>
            <Permission allowedRoles={[ATTORNEY, PARALEGAL]}>
                <Col md={6} sm={6} xl={3}>
                    <Card className="custom-card">
                        <Card.Body className="text-center">
                            <div className="icon-service bg-primary-transparent rounded-circle text-primary">
                                <i className="fe fe-user"></i>
                            </div>
                            <p className="mb-1 text-muted">Custom Label 3</p>
                            <h3 className="mb-0">0</h3>
                        </Card.Body>
                    </Card>
                </Col>
            </Permission>
            <Permission allowedRoles={[ATTORNEY, PARALEGAL]}>
                <Col md={6} sm={6} xl={3}>
                    <Card className="custom-card">
                        <Card.Body className="text-center">
                            <div className="icon-service bg-primary-transparent rounded-circle text-primary">
                                <i className="fe fe-user"></i>
                            </div>
                            <p className="mb-1 text-muted">Custom Label 4</p>
                            <h3 className="mb-0">0</h3>
                        </Card.Body>
                    </Card>
                </Col>
            </Permission>
        </Row>
    )
}

export { OverviewTiles, CaseGraphs, OpenCasesListView, CustomTileView }
